services:
  app: 
    build: ./app
    restart: always
    depends_on:
      - db
    env_file:
      - .env

  2fa:
    build: ./2fa
    restart: always
    depends_on:
      - db
    env_file:
      - .env

  scheduler: 
    build: ./scheduler
    restart: always
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - ./postgres-data:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
      - 2fa
